
2.	From input layer to hidden layer we have    3 neurons * 4 hidden neurons = 12 weights and each hidden neuron has 1 bias = 4 biases . 
From hidden layer 4 neurons to output neuron layer  4 weights and 1 bias

Total 16  weights and 5 biases


In [12]:
#q3
import numpy as np
np.random.seed(42)
input = 3
weights = np.random.randn(input)
bias = np.random.randn()
print("Weights:", weights)
print("Bias:", bias)

Weights: [ 0.49671415 -0.1382643   0.64768854]
Bias: 1.5230298564080254


q4
z=  (2*0.1 + 3*0.4 + 5*0.2) +1
z=3.4

In [13]:
# q5 
# weights determins the connection strenght between neurons 
# bias is an extra parameter that helps neurons to fire or stay quite 

q6

the neural network can't learn patterns effictlively . because at starting all neurons stat with 0 weight and during forward propagation they produce same output and during backward propagation they all updated with same gradients.. 

Q7
inputs : are the scaled values which are passed to a neurons in neural network and later on in training process these are affected by two parameters called weights and biases.

weights determins the connection strenght between neurons 
bias is an extra parameter that helps neurons to fire or stay quite 

activation functions introduces the non linearity to the network and helps to network to identify complex patterns in data or inputs.

q8 drawing is in pdf file 

input layer has 4 neurons , 2 hidden layers have 5 neurons each means total 10 neurons in hidden layers and 3 neurons in output layer . toatl 4+`0+3=17

they output layer might have a softmax activation fuction because it going to predict the output probablities for 3 categories . 

In [14]:
#q9

import pandas as pd

data={"hours_study":[4,5,6,7,8,9,10,11,12,13,14,15],
"exam_score":[35,40,45,50,55,60,65,70,75,80,85,90]
}
df=pd.DataFrame(data)


In [15]:
#q10

batch_size = 3
batches = np.split(df, len(df) // batch_size)
for i, batch in enumerate(batches, start=1):
    print(f"Batch {i}:")
    print(batch)
    print()
print("Total number of batches:", len(batches))

Batch 1:
[[ 4 35]
 [ 5 40]
 [ 6 45]]

Batch 2:
[[ 7 50]
 [ 8 55]
 [ 9 60]]

Batch 3:
[[10 65]
 [11 70]
 [12 75]]

Batch 4:
[[13 80]
 [14 85]
 [15 90]]

Total number of batches: 4


In [16]:
#q11
for i in range(0, len(df), batch_size):
    batch = df.iloc[i:i + batch_size]
    print(f"Batch {(i // batch_size) + 1}:")
    print(batch)
    print()

Batch 1:
   hours_study  exam_score
0            4          35
1            5          40
2            6          45

Batch 2:
   hours_study  exam_score
3            7          50
4            8          55
5            9          60

Batch 3:
   hours_study  exam_score
6           10          65
7           11          70
8           12          75

Batch 4:
    hours_study  exam_score
9            13          80
10           14          85
11           15          90



q12
Batch gradient descent

q13 

stochastic gradient descent

q14 
 3 batches


Q15

the trainig takes less time , and effectively the parameters (weights and biases) get updated , for each batch once parameters are updated . 

q16
number of batches for epochs is 4

q17
epoch = in 1 epoch the model will train or see complete training dataset once. 

q18
in one epoch 4 times the weights gets updated.

q19
20 batch iterations occurs

In [17]:

for epoch in range(1, 4):      
    for batch in range(1, 5):  
        print(f"Epoch {epoch}, Batch {batch}")

Epoch 1, Batch 1
Epoch 1, Batch 2
Epoch 1, Batch 3
Epoch 1, Batch 4
Epoch 2, Batch 1
Epoch 2, Batch 2
Epoch 2, Batch 3
Epoch 2, Batch 4
Epoch 3, Batch 1
Epoch 3, Batch 2
Epoch 3, Batch 3
Epoch 3, Batch 4


q 21
the model gets few opportunities to look into complete dataset. it identifies very few patterns . So it performs poorly 

q22
if we train the model for too many epochs , then model will remember the training dataset insted of identifing the patterns . that leads to overfitting.

In [18]:
samples=500
batch_size=20
epoch= samples // batch_size
print(epoch)

25


q24 

batch= a batch holds a subset dataset of complete dataset. 
epoch = it holds complete dataset . 

q25 
after the loss function calculating the loss. the optimizer with the help of learning rate updates the parameters(weights and biases) of model . it adjust's the parameters to reduce the loss .

q26
adam, adamW, sgd .

q27
W = (old)W - learning_rate * dW



b = (old)b - learning_rate * db

q28
after whole dataset

q29

after each sample

q30

adv:calculates accurate gradient (loss). 
dis: requires more time to train on complete dataset and very complex when dealing with larger datasets.


q31
 One advantage of Stochastic Gradient Descent (SGD) is that it updates the model more frequently, so it can learn faster on large datasets. One disadvantage is that the updates are noisy, so the loss may fluctuate and convergence can be less stable.

In [19]:
#q32
import numpy as np

weight = 0.5
gradient = 0.2
learning_rate = 0.1

weight = weight - learning_rate * gradient
print("Updated weight:", weight)

Updated weight: 0.48


#q33
 The Adam optimizer gets its name from "Adaptive Moment Estimation". It combines momentum (using moving averages of past gradients) and adaptive learning rates (using moving averages of squared gradients).

q34
Adam is considered a good default choice because it usually trains faster, converges more smoothly, and works well on many deep learning tasks without needing too much manual tuning.

q35. If the learning rate is too high, the model may overshoot the minimum, causing unstable training or even divergence.

q36. If the learning rate is too low, training becomes very slow, and the model may take too many epochs to learn properly.

q37

The purpose of an activation function is to add non-linearity to the neural network so it can learn complex patterns instead of only simple straight-line relationships.

q38. The Sigmoid activation function is:

sigma(x) = 1 / (1 + e^(-x))

q39
The ReLU activation function is:

ReLU(x) = max(0, x)

Q40.  
ReLU(-5) = 0  
ReLU(0) = 0  
ReLU(7) = 7

Q41. For the Binary Step function:  
if x < 0, output = 0  
if x >= 0, output = 1  
So:  
Binary Step(-2) = 0  
Binary Step(3) = 1

Q42. The Sigmoid function outputs values in the range (0, 1).

Q43. The Tanh function outputs values in the range (-1, 1).

q44. Tanh is often preferred over Sigmoid in hidden layers because it is zero-centered, which can help gradients flow more effectively and sometimes improve training.

q45. The Softmax function is usually used in the output layer for multi-class classification problems, where we want probabilities for several classes.

In [20]:
# Q46
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

x = 2
print(sigmoid(x))

0.8807970779778823


In [21]:
# Q47
def relu(values):
    return [max(0, v) for v in values]

values = [-3, -1, 0, 4, 7]
print(relu(values))

[0, 0, 0, 4, 7]


q48. A neural network cannot learn complex patterns if it uses only linear activation functions because the combination of linear functions is still linear. That means it can only learn straight-line relationships and cannot model non-linear patterns.

q49. Matching activation functions to output ranges:

 Binary Step {0, 1}
 Linear (-∞, ∞)
  Sigmoid (0, 1)
 Tanh  (-1, 1)
 ReLU  [0, ∞)
  Softmax each output is between 0 and 1, and all outputs sum to 1


Q50. For the Softmax calculation with raw scores [2.0, 1.0, 0.1]:

Step 1: Compute exponentials  
e^2 = 7.389  
e^1 = 2.718  
e^0.1 = 1.105  

Step 2: Add them  
Sum = 7.389 + 2.718 + 1.105 = 11.212  

Step 3: Probability of Class 1  
P(Class 1) = e^1 / Sum = 2.718 / 11.212 ≈ 0.242

So, the probability of Class 1 is approximately 0.242 or 24.2%.